### PR TITLE
Update ripple-libpp to 1.0.0-b4

### PR DESCRIPTION
**Pull request by ximinez**

### CODE REVIEW

**Comment by ximinez** [comment]
Sure. I went ahead and squashed, BTW, since it doesn't make much sense to have to library updates in one PR. I am a little concerned by the drastic drop in coverage, though, and I don't think it has anything to do with the lib.

**Comment by wilsonianb** [comment]
It looks like Travis didn't actually run the tests
https://travis-ci.org/ripple/validator-keys-tool/builds/336681549#L1388

Here's a previous successful run
https://travis-ci.org/ripple/validator-keys-tool/builds/225727022#L3837

**Comment by wilsonianb** [comment]
I see now.
`.travis.yml` needs `APP_ARGS=--unittest`
https://github.com/ripple/rippled/commit/f7a7f13287d17d91b029ef32a64dfac1ef42a071
I'll open a `0.2.0` pr with that change

**Comment by ximinez** [comment]
Good catch!

**Comment by wilsonianb** [comment]
merged as https://github.com/ripple/validator-keys-tool/commit/5714c26692c9f3c7efbe0cd01a60bc878b3c309e in https://github.com/ripple/validator-keys-tool/pull/6

**Pull request closed without merging**
